const SUPABASE_URL = "https://dxzprpbpneeosimpnobz.supabase.co";
const SUPABASE_KEY = "sb_publishable_y_XCOzunbj26QVgJuG8DmQ_K7OABDrp";
const form = document.getElementById("bookingForm");
const result = document.getElementById("bookingResult");
const dateInput = document.getElementById("date");
const timeInput = document.getElementById("time");
document.getElementById("year").textContent = new Date().getFullYear();
const today = new Date();
const localToday = new Date(today.getTime() - today.getTimezoneOffset()*60000).toISOString().split("T")[0];
dateInput.min = localToday;
function showResult(message,success=true){result.style.display="block";result.innerHTML=message;result.style.background=success?"rgba(72,200,130,.12)":"rgba(230,80,80,.12)";result.style.borderColor=success?"rgba(72,200,130,.25)":"rgba(230,80,80,.25)";result.style.color=success?"#b9f1d1":"#ffc0c0";}
async function loadBookedTimes(){const d=dateInput.value;if(!d)return;try{const r=await fetch(`${SUPABASE_URL}/rest/v1/bookings?booking_date=eq.${encodeURIComponent(d)}&select=booking_time`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!r.ok)throw new Error("fetch failed");const bookings=await r.json();const booked=new Set(bookings.map(x=>x.booking_time));[...timeInput.options].forEach(o=>{if(o.value)o.disabled=booked.has(o.value)});if(booked.has(timeInput.value))timeInput.value="";}catch(e){console.error(e)}}
dateInput.addEventListener("change",loadBookedTimes);
form.addEventListener("submit",async e=>{e.preventDefault();const name=document.getElementById("name").value.trim(),phone=document.getElementById("phone").value.trim(),email=document.getElementById("email").value.trim(),date=dateInput.value,time=timeInput.value,message=document.getElementById("message").value.trim();if(!name||!phone||!email||!date||!time){showResult("يرجى تعبئة جميع الحقول المطلوبة.",false);return}const btn=form.querySelector(".submit-button");btn.disabled=true;btn.textContent="جاري تأكيد الحجز...";try{const r=await fetch(`${SUPABASE_URL}/rest/v1/bookings`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({name,phone,email,booking_date:date,booking_time:time,message})});if(r.ok){const fd=new Date(date+"T00:00:00").toLocaleDateString("ar-JO",{year:"numeric",month:"long",day:"numeric"});showResult(`تم تأكيد الحجز بنجاح لـ <strong>${escapeHtml(name)}</strong> بتاريخ <strong>${fd}</strong> الساعة <strong>${escapeHtml(time)}</strong>.`);form.reset();dateInput.min=localToday;[...timeInput.options].forEach(o=>o.disabled=false);return}const err=await r.json().catch(()=>({}));if(r.status===409||err.code==="23505"){showResult("هذا الموعد محجوز مسبقاً. اختر تاريخاً أو وقتاً آخر.",false);await loadBookedTimes()}else{console.error(err);showResult("حدث خطأ أثناء حفظ الحجز. تأكد من إعدادات Supabase ثم حاول مرة أخرى.",false)}}catch(err){console.error(err);showResult("تعذر الاتصال بقاعدة البيانات. تأكد من اتصال الإنترنت وحاول مرة أخرى.",false)}finally{btn.disabled=false;btn.textContent="تأكيد طلب الحجز"}});
function escapeHtml(text){const d=document.createElement("div");d.textContent=text;return d.innerHTML}
